// scripts/sitemap.mjs
//
// Generates public/sitemap.xml from what the site actually has. Same approach as the
// studio repo's scripts/sitemap.mjs, deliberately, so both behave alike.
//
// WHERE EACH URL COMES FROM
//   static   the STATIC list below
//   log      one per published entry, taken from publishedPosts() by importing the data
//            module rather than by regex, so a draft or a coming soon piece can never
//            leak into the sitemap. Those have no page to land on and advertising them
//            earns a soft 404.
//
// LASTMOD IS REAL, the date of the last commit that touched the source file. A sitemap
// where every line claims today is one that cries wolf and gets weighed accordingly.
//
// EXCLUSIONS come from public/robots.txt so the two files cannot disagree. The bridge,
// the helm and the map are login gated and must never be listed.
//
// changefreq and priority are deliberately absent, google has ignored both for years.
//
// Run: node scripts/sitemap.mjs
// No oxford commas, no dashes.

import fs from 'fs';
import path from 'path';
import { execFileSync } from 'child_process';
import { pathToFileURL } from 'url';

const SITE = 'https://burroship.com';
const ROOT = process.cwd();

const STATIC = ['/', '/log/', '/contact/', '/build/', '/deploy/', '/automate/', '/rewards/'];

const disallowed = fs.readFileSync(path.join(ROOT, 'public/robots.txt'), 'utf8')
  .split('\n')
  .filter((l) => l.trim().toLowerCase().startsWith('disallow:'))
  .map((l) => l.split(':')[1].trim())
  .filter(Boolean);

const isAllowed = (url) => !disallowed.some((d) => url.startsWith(d));

const repoDate = execFileSync('git', ['log', '-1', '--format=%cs'], { cwd: ROOT }).toString().trim();
const lastmod = (file) => {
  if (!file || !fs.existsSync(path.join(ROOT, file))) return repoDate;
  try {
    const d = execFileSync('git', ['log', '-1', '--format=%cs', '--', file], { cwd: ROOT }).toString().trim();
    return d || repoDate;
  } catch {
    return repoDate;
  }
};

const entries = new Map();
const add = (url, file) => {
  let u = url.endsWith('/') ? url : url + '/';
  if (!isAllowed(u)) return;
  entries.set(u, lastmod(file));
};

for (const url of STATIC) {
  const guess = 'src/pages' + url.replace(/\/$/, '') + '/index.jsx';
  add(url, fs.existsSync(path.join(ROOT, guess)) ? guess : null);
}

const logMod = await import(pathToFileURL(path.join(ROOT, 'src/data/log.js')).href);
for (const post of logMod.publishedPosts()) {
  add(`/log/${post.slug}/`, 'src/data/log.js');
}

const urls = [...entries.entries()].sort(([a], [b]) => a.localeCompare(b));

const xml =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<!--\n` +
  `  Generated by scripts/sitemap.mjs. Do not hand edit, the next run overwrites it.\n` +
  `  ${urls.length} urls. lastmod is the real date each page's source last changed.\n` +
  `  The bridge, the helm and the map are login gated and excluded via robots.txt.\n` +
  `-->\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  urls.map(([u, d]) => `  <url>\n    <loc>${SITE}${u}</loc>\n    <lastmod>${d}</lastmod>\n  </url>`).join('\n') +
  `\n</urlset>\n`;

fs.writeFileSync(path.join(ROOT, 'public/sitemap.xml'), xml);
console.log(`[sitemap] wrote ${urls.length} urls`);
console.log(`[sitemap]   excluded per robots.txt: ${disallowed.join(' ')}`);
