#!/usr/bin/env python3
"""
build_deploy_script.py — Template for assembling a self-installing
shell script from a directory of staged files.
 
Used by the bulk-file-delivery skill. Copy this file, customize the
CONFIG section, and run.
 
Generates a shell script that:
- Archives existing files (does not delete) before overwriting
- Creates directories with mkdir -p before writing
- Uses unique heredoc markers per file (collision-checked)
- Prints progress as it goes
- Prints next steps at end
"""
 
from pathlib import Path
 
# ============ CONFIG — CUSTOMIZE THESE ============
 
PROJECT_NAME = "my-project"
SRC = Path("/home/claude/delivery/files")
OUT = Path("/mnt/user-data/outputs/deploy.sh")
 
# Files to include, in the order they should be written.
# Paths are relative to the target repo root.
ORDER = [
    # "docs/DESIGN.md",
    # "src/styles/index.css",
    # "src/App.jsx",
]
 
# Old files/directories to archive before writing the new ones.
# Format: list of paths (relative to repo root)
ARCHIVES = [
    # "src/components/Footer",
    # "src/components/Header",
]
 
# Empty directories that might be left behind. Removed if empty.
DIRS_TO_REMOVE_IF_EMPTY = [
    # "src/hooks",
]
 
# Build tool cache to clear at end
CACHE_CLEAR = "rm -rf node_modules/.vite"
 
# Sanity-check file (presence proves we are in the right directory)
SANITY_FILE = "package.json"
 
# Marker prefix for heredocs — keep short and unique per project
MARKER_PREFIX = f"{PROJECT_NAME.upper().replace('-', '_')}_EOF_"
 
# Optional surgical edits via sed. Each entry is a tuple of
# (file_path, sed_pattern, description). Applied before file writes.
SURGICAL_EDITS = [
    # ("src/App.jsx", "/CoordinateBar/d", "Remove CoordinateBar import"),
]
 
# ============ HEADER / FOOTER TEMPLATES ============
 
def build_archive_block():
    lines = []
    for p in ARCHIVES:
        if "/" in p and not p.endswith((".md", ".jsx", ".js", ".css", ".json")):
            # Likely a directory
            lines.append(f'[ -d "{p}" ] && mv "{p}" "$ARCHIVE_DIR/" || true')
        else:
            # Likely a file
            lines.append(f'[ -f "{p}" ] && mv "{p}" "$ARCHIVE_DIR/" || true')
    return "\n".join(lines)
 
def build_rmdir_block():
    return "\n".join(
        f'[ -d "{d}" ] && [ -z "$(ls -A {d} 2>/dev/null)" ] && rmdir {d} || true'
        for d in DIRS_TO_REMOVE_IF_EMPTY
    )
 
def build_sed_block():
    lines = []
    for filepath, pattern, desc in SURGICAL_EDITS:
        lines.append(f'echo "  surgical edit: {desc}"')
        lines.append(f'if [ -f "{filepath}" ]; then')
        lines.append(f'  sed -i.bak \'{pattern}\' "{filepath}"')
        lines.append(f'  rm -f "{filepath}.bak"')
        lines.append('fi')
    return "\n".join(lines)
 
def build_header():
    return f"""#!/bin/bash
# {PROJECT_NAME}-deploy.sh
# Auto-generated by bulk-file-delivery skill.
# Run from the project repo root.
 
set -e
 
if [ ! -f "{SANITY_FILE}" ]; then
  echo "ERROR: run this from the repo root (where {SANITY_FILE} lives)"
  exit 1
fi
 
STAMP=$(date +%Y%m%d_%H%M%S)
ARCHIVE_DIR="_archive/$STAMP"
 
echo ""
echo "============================================="
echo "  {PROJECT_NAME} deploy"
echo "============================================="
echo ""
echo "Archiving old files to $ARCHIVE_DIR ..."
mkdir -p "$ARCHIVE_DIR"
 
{build_archive_block()}
 
{build_rmdir_block()}
 
{build_sed_block()}
 
echo "Writing files ..."
"""
 
def build_footer():
    return f"""
 
echo ""
echo "Clearing build cache ..."
{CACHE_CLEAR}
 
echo ""
echo "============================================="
echo "  Done. {len(ORDER)} files written."
echo "============================================="
echo ""
echo "Verify with: yarn dev"
echo ""
echo "When happy:"
echo "  git add -A"
echo "  git commit -m 'your message here'"
echo "  git push"
echo ""
"""
 
# ============ BUILD ============
 
def build():
    parts = [build_header()]
    
    for i, rel in enumerate(ORDER, start=1):
        marker = f"{MARKER_PREFIX}{i:02d}"
        src_path = SRC / rel
        
        if not src_path.exists():
            raise FileNotFoundError(f"Missing source file: {src_path}")
        
        content = src_path.read_text()
        
        # Collision check
        if marker in content:
            raise ValueError(
                f"Marker collision in {rel}. "
                f"Choose a different MARKER_PREFIX."
            )
        
        parts.append(f'\necho "  -> {rel}"\n')
        parts.append(f"cat > \"{rel}\" << '{marker}'\n")
        parts.append(content)
        if not content.endswith("\n"):
            parts.append("\n")
        parts.append(f"{marker}\n")
    
    parts.append(build_footer())
    
    OUT.write_text("".join(parts))
    OUT.chmod(0o755)
    
    print(f"Wrote {OUT}")
    print(f"Total lines: {sum(1 for _ in open(OUT))}")
    print(f"Total bytes: {OUT.stat().st_size}")
    print(f"Files included: {len(ORDER)}")
    print()
    print("Now test in a sandbox before sending to user:")
    print(f"  SANDBOX=/tmp/{PROJECT_NAME}-test")
    print(f"  rm -rf $SANDBOX && mkdir -p $SANDBOX && cd $SANDBOX")
    print(f"  touch {SANITY_FILE}")
    print(f"  bash {OUT}")
    print(f"  find $SANDBOX -type f | wc -l  # should be {len(ORDER) + 1}")
 
if __name__ == "__main__":
    build()
